version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - /home/hiroakik4/42/Inception/data/wp:/var/www/html
    networks:
      - app_network

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - /home/hiroakik4/42/Inception/data/wp:/var/www/html
    networks:
      - app_network

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db:
