version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - app_network

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - wp:/var/www/html
    networks:
      - app_network

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    # volumes:
    #   - /home/hiroakik4/42/volumes/db:/var/www/html
    networks:
      - app_network

networks:
  app_network:

volumes:
  wp:
  db:
