version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - shared-volume:/var/www/html
    networks:
      - frontend

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - shared-volume:/var/www/html
    networks:
      - frontend

  mariadb:
    build: ./requirements/mariadb

networks:
  frontend:
  backend:

volumes:
  shared-volume:
