version: "3"

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - /home/hiroakik4/42/Inception/data/wp:/var/www/html
    networks:
      - app_network
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: ./requirements/wordpress
    ports:
      - "9000:9000"
    volumes:
      - /home/hiroakik4/42/Inception/data/wp:/var/www/html
    networks:
      - app_network
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - app_network
    restart: always
    env_file:
      - app.env

networks:
  app_network:

volumes:
  db:
